config/routes.rb
GoldApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :value_inquiries, only: [:new, :create, :update, :destroy]
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/models/gold_value_inquiry.rb
class GoldValueInquiry < ActiveRecord::Base
	belongs_to :user
	validates :UserId, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :value_inquiry, dependent: :destroy
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  									format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    ValueInquiry.where("user_id = ?", id)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/value_inquiry.rb
class ValueInquiry < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :karat, presence: true, length: { maximum: 8 }
	validates :weight, presence: true, length: { maximum: 8 }, numericality: true#{greater_than: 0, message: "Weight must be a number"}
	validates :market_price, presence: true, length: { maximum: 8 }
	validates :value, presence: true, length: { maximum: 8 }
	validates :user_id, presence: true

#	require application_helper
#	before_save {|ValueInquiry| value_inquiry.value = ((@karat / @pure_gram_karat) * (@market_price / @troy_ounce) * @weight)} 
#	@inquiry = ValueInquiry.find(:last)
#	@inquiry.calculate_value

#	def calculate_value
#		write_attribute(:value, @gold_value)
#	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
  	  @value_inquiry = current_user.value_inquiry.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  	@karat_list = {'24 Karat' => '24' , 
                   '23 Karat' => '23' , 
                   '22 Karat' => '22' , 
                   '21 Karat' => '21' , 
                   '20 Karat' => '20' , 
                   '19 Karat' => '19' , 
                   '18 Karat' => '18' , 
                   '16 Karat' => '16' , 
                   '14 Karat' => '14' , 
                   '12 Karat' => '12' , 
                   '10 Karat' => '10' }

#     response = HTTParty.get(http://www.quandl.com/api/v1/datasets/BUNDESBANK/BBK01_WT5511.json?trim_start=2014-01-01&trim_end=2014-02-02)

#    start_date = Time.now.strftime("%Y-%m-%d")
    response = HTTParty.get("http://www.quandl.com/WGC/GOLD_DAILY_USD.json?trim_start=2014-02-02")
#   params = {"trim_start" => "2014-01-02"}
    body = JSON.parse(response.body)
    @data = body["data"]
    h1 = Hash[*@data.flatten]
#   k = Time.now.strftime("%Y-%m-%d") #'2014-01-08'
    @latest_price = h1.values[0]
    @latest_date = h1.keys[0]

  end

  def create
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @value_inquiry = @user.value_inquiry.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
    	flash[:success] = "Welcome to the Gold Price Calculator!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/value_inquiries_controller.rb
class ValueInquiriesController < ApplicationController
  before_action :signed_in_user, only: [:create, :update, :destroy]
  
  def index
  end
    
  def create
    @pure_gram_karat = 24
    @troy_ounce = 31.1
    @karat = params[:value_inquiry][:karat].to_f
    @weight = params[:value_inquiry][:weight].to_f
    @market_price = params[:value_inquiry][:market_price].to_f

    @gold_value = ((@karat / @pure_gram_karat) * (@market_price / @troy_ounce) * @weight).round(2)

#    binding.pry
    # this is to assign a calculated number to the value field
#    value_inquiry_params[:value] = @gold_value # assignment wont work
#    @value_inquiry = current_user.value_inquiry.build(params[:value_inquiry])
      puts 'ValueInquiriesController *******************'
      puts params[:value_inquiry]
      puts @karat
      puts @weight
      puts @market_price
      puts "GoldValue: #{@gold_value}"
      puts '******************* ValueInquiriesController'

#      @value_inquiry = current_user.value_inquiry.build(value_inquiry_params)
    @value_inquiry = current_user.value_inquiry.new(:karat => @karat, :weight => @weight, :market_price => @market_price, :value => @gold_value)


    if @value_inquiry.save
      flash[:success] = "Your gold is valued at $" + @value_inquiry.value.to_s+ ". Your Inquiry has been saved!"

      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end


  def value_inquiry_params
#    @value = (params[][:karat]/value_inquiry_params[:pure_gram_karat])*@puregram
    params.require(:value_inquiry).permit(:karat, :weight, :market_price)
#    value_inquiry_params.update(:value)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Gold Jewelery Price Calculator"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

#  @pure_gram_karat = 24
#  @troy_ounce = 31.1

end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def karat_list_holder
	  	{'24 Karat' => '24' , 
                   '23 Karat' => '23' , 
                   '22 Karat' => '22' , 
                   '21 Karat' => '21' , 
                   '20 Karat' => '20' , 
                   '19 Karat' => '19' , 
                   '18 Karat' => '18' , 
                   '16 Karat' => '16' , 
                   '14 Karat' => '14' , 
                   '12 Karat' => '12' , 
                   '10 Karat' => '10' }
  end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Gold Price Calculator</a>
    by Abey Mathew
  </small>
  <nav>
    <ul>
      <!--li><%= link_to "About",   about_path %></li-->
      <!--li><%= link_to "Contact", contact_path %></li-->
      <li><a href="http://goldnews.bullionvault.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Gold App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <!--li><%= link_to "Users", '#' %></li-->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <!--li><%= link_to "Settings", '#' %></li-->
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="value_inquiries">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%#= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %> made an inquiry for
  </span>
  <span class="weight"><%= feed_item.weight %> grams @</span>
  <span class="karat"><%= feed_item.karat %> karat</span>
  <span class="value">was valued at <%= feed_item.value %></span>
  <span class="market_price"> when a Troy ounce was priced at <%= feed_item.market_price %></span>
    <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.value_inquiry.count, "inquiry") %>
</span>

app/views/shared/_value_inquiry_form.html.erb
<%= form_for(@value_inquiry) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.hidden_field :market_price, value: @latest_price %>

<table>
	<tr>
		<td><div class="field inline">
			<%= f.label :"Gold Purity in Karats"%>
			<%= f.collection_select(:karat, karat_list_holder, :last, :first)%>
			<%= f.label :"Gold Weight"%>
			<%= f.text_field :weight, placeholder: "Enter Gold Weight in Grams", type: "number"  %>
			<br/><br/>
			<span> Gold Price is $<%=@latest_price%>/Troy ounce as of <%=@latest_date%></span>
			<br/>
		</div></td>
		<td><a href="http://www.goldline.com/gold-prices-charts" title="Gold Prices"><img src="http://www.goldline.com/widgets/?metal=gold&size=lg" border="0" target="_blank" title="Gold Prices Chart" alt="Gold Prices Chart"></a>
		</td>
	</tr>
</table>

<%= f.submit "Submit & Save Inquiry", class: "btn btn-large btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	The Gold Price Calculator is a project to learn how to make a site in Ruby to get rammed up on Ruby on Rails.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact WFA about the Gold app at the
  <a href="http://gold.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
	Learn more about things made out of Gold from these sites
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class =".span8">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/value_inquiry_form' %>
      </section>
    </aside>
      <div class=".span6">
      <h3>Inquiry Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center hero-unit">
<h1>Gold App</h1>
<h2>
	Welcome to the Gold Jewelery Price Calculator home page.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("golden-mercedes-wallpaper.jpg", alt: "Gold"), 'http://blogs-images.forbes.com' %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span2">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.value_inquiry.any? %>
      <h3>Inquiries (<%= @user.value_inquiry.count %>)</h3>
      <ol class="value_inquiry">
        <%= render @value_inquiry %>
      </ol>
      <%= will_paginate @value_inquiry %>
    <% end %>
  </div>
</div>

app/views/value_inquiries/_value_inquiry.html.erb
<li>
  <span class="weight"><%= value_inquiry.weight %> grams @</span>
  <span class="karat"><%= value_inquiry.karat %> karat</span>
  <span class="value">was valued at <%= value_inquiry.value %></span>
  <span class="market_price"> when a Troy ounce was priced at <%= value_inquiry.market_price %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(value_inquiry.created_at) %> ago.
  </span>
</li>